### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by uniuuu** [dinushchathurya/terrafrom-eks#1]
Typo in the name of the repository: terra**fr**om-eks

[**terrafrom**-eks](https://github.com/dinushchathurya/**terrafrom**-eks)

**Comment by dinushchathurya** [comment]
Thank you for bringing this to my attention I have fixed the issue. Thank you for your understanding and for your support of this project.

**Comment by uniuuu** [comment]
Sure, I am using it for testing Terraform visualization like **Pluralith** and *Brainboard*.

**Comment by uniuuu** [comment]
Take a look at it. Nice!
![project_pluralith-local-project%2Frun_4622131%2Frun_4622131_1675654428966](https://user-images.githubusercontent.com/26146469/216878442-886a367c-3f47-4c25-a389-da5f77b83ebf.png)

**Comment by dinushchathurya** [comment]
What do you think about it? Is it useful to you?
